/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/signup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Signup */
    post: operations['signup_api_auth_signup_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations['login_api_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout_api_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations['me_api_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/google': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Google Start */
    get: operations['google_start_api_auth_google_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/google/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Google Callback */
    get: operations['google_callback_api_auth_google_callback_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/onboarding': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Onboarding */
    patch: operations['update_onboarding_api_me_onboarding_patch']
    trace?: never
  }
  '/api/me/onboarding/submit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit Onboarding */
    post: operations['submit_onboarding_api_me_onboarding_submit_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/onboarding/reopen': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reopen Onboarding */
    post: operations['reopen_onboarding_api_me_onboarding_reopen_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/photo': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Upload Photo */
    put: operations['upload_photo_api_me_photo_put']
    post?: never
    /** Delete Photo */
    delete: operations['delete_photo_api_me_photo_delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/telegram/webhook': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Telegram Webhook */
    post: operations['telegram_webhook_api_telegram_webhook_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Users */
    get: operations['list_users_api_admin_users_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/brands/{brand_id}/art-directors/{art_director_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Assign Art Director */
    put: operations['assign_art_director_api_admin_brands__brand_id__art_directors__art_director_id__put']
    post?: never
    /** Unassign Art Director */
    delete: operations['unassign_art_director_api_admin_brands__brand_id__art_directors__art_director_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/admin/art-directors/{art_director_id}/creators/{creator_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Assign Creator */
    put: operations['assign_creator_api_admin_art_directors__art_director_id__creators__creator_id__put']
    post?: never
    /** Unassign Creator */
    delete: operations['unassign_creator_api_admin_art_directors__art_director_id__creators__creator_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AdminUsersResponse
     * @description Все пользователи, кроме админов, новые первыми, и все связки между ними.
     */
    AdminUsersResponse: {
      /** Users */
      users: components['schemas']['ManagedUser'][]
      /** Brand Art Directors */
      brand_art_directors: components['schemas']['BrandArtDirectorLink'][]
      /** Art Director Creators */
      art_director_creators: components['schemas']['ArtDirectorCreatorLink'][]
    }
    /** ArtDirectorCreatorLink */
    ArtDirectorCreatorLink: {
      /**
       * Art Director Id
       * Format: uuid
       */
      art_director_id: string
      /**
       * Creator Id
       * Format: uuid
       */
      creator_id: string
      /**
       * Assigned At
       * Format: date-time
       */
      assigned_at: string
    }
    /** Body_upload_photo_api_me_photo_put */
    Body_upload_photo_api_me_photo_put: {
      /** Photo */
      photo: string
    }
    /** BrandArtDirectorLink */
    BrandArtDirectorLink: {
      /**
       * Brand Id
       * Format: uuid
       */
      brand_id: string
      /**
       * Art Director Id
       * Format: uuid
       */
      art_director_id: string
      /**
       * Assigned At
       * Format: date-time
       */
      assigned_at: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string
    }
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string
      /** Password */
      password: string
    }
    /** ManagedUser */
    ManagedUser: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Email */
      email: string
      /** Name */
      name: string | null
      role: components['schemas']['Role'] | null
      status: components['schemas']['Status']
      /** Photo Url */
      photo_url: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** MeResponse */
    MeResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Email */
      email: string
      role: components['schemas']['Role'] | null
      status: components['schemas']['Status']
      /** Name */
      name: string | null
      /** Photo Url */
      photo_url: string | null
      /** Is Admin */
      is_admin: boolean
      /**
       * Onboarding Step
       * @description Шаг, с которого продолжить онбординг: первый незаполненный, иначе проверка.
       */
      readonly onboarding_step: ('role' | 'profile' | 'review') | null
    }
    /**
     * OnboardingUpdate
     * @description Ответы шага онбординга. Неуказанные поля не меняются.
     */
    OnboardingUpdate: {
      role?: components['schemas']['Role'] | null
      /** Name */
      name?: string | null
    }
    /**
     * Role
     * @description Кто пользователь в продукте. Решает, что доступно внутри.
     * @enum {string}
     */
    Role: 'brand' | 'art_director' | 'creator'
    /** SignupRequest */
    SignupRequest: {
      /**
       * Email
       * Format: email
       */
      email: string
      /** Password */
      password: string
    }
    /**
     * Status
     * @description Где аккаунт в жизненном цикле. Решает, пускать ли в продукт вообще.
     * @enum {string}
     */
    Status: 'onboarding' | 'pending_review' | 'approved' | 'rejected'
    /** TelegramCallbackQuery */
    TelegramCallbackQuery: {
      /** Id */
      id: string
      from: components['schemas']['TelegramUser']
      message?: components['schemas']['TelegramMessage'] | null
      /** Data */
      data?: string | null
    }
    /** TelegramChat */
    TelegramChat: {
      /** Id */
      id: number
    }
    /** TelegramMessage */
    TelegramMessage: {
      /** Message Id */
      message_id: number
      chat: components['schemas']['TelegramChat']
    }
    /** TelegramUpdate */
    TelegramUpdate: {
      /** Update Id */
      update_id: number
      callback_query?: components['schemas']['TelegramCallbackQuery'] | null
    }
    /** TelegramUser */
    TelegramUser: {
      /** Id */
      id: number
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  signup_api_auth_signup_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  login_api_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  me_api_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  google_start_api_auth_google_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  google_callback_api_auth_google_callback_get: {
    parameters: {
      query?: {
        code?: string | null
        state?: string | null
      }
      header?: never
      path?: never
      cookie?: {
        google_oauth?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_onboarding_api_me_onboarding_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['OnboardingUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_onboarding_api_me_onboarding_submit_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  reopen_onboarding_api_me_onboarding_reopen_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  upload_photo_api_me_photo_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_photo_api_me_photo_put']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_photo_api_me_photo_delete: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  telegram_webhook_api_telegram_webhook_post: {
    parameters: {
      query?: never
      header?: {
        'X-Telegram-Bot-Api-Secret-Token'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TelegramUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_users_api_admin_users_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AdminUsersResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  assign_art_director_api_admin_brands__brand_id__art_directors__art_director_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        brand_id: string
        art_director_id: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  unassign_art_director_api_admin_brands__brand_id__art_directors__art_director_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        brand_id: string
        art_director_id: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  assign_creator_api_admin_art_directors__art_director_id__creators__creator_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        art_director_id: string
        creator_id: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  unassign_creator_api_admin_art_directors__art_director_id__creators__creator_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        art_director_id: string
        creator_id: string
      }
      cookie?: {
        session?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
